### ISSUE TITLE
Address and Note fields disappeared from node form in app.

### ISSUE THREAD

**Issue by vlkff** [vlkff/reiscout-com#1]
Address(field_address_text) and Notes (body) fields disappeared from node form in app.
They both are present in reiscout_property_form_alter hook.

**Comment by Digeridoo** [comment]
Fixed. Several fields were with the same weight here http://grabilla.com/06407-fe094476-53f0-4578-9fe3-fdc3db976a93.png. Weight of fields must be unique. Otherwise app may fall to render field.
